### ISSUE TITLE
issue with invaild/irregular characters in filename (such as the '/')

### ISSUE THREAD

**Issue by PatrickJRed** [MeowOrange/matrix-archive#5]
Importing keys. This may take a while...
Selected room: ...:matrix.org
Fetching ...:matrix.org room messages (aka ...) and writing to disk...
Database ready for room: ...
Fetch done!3 events for room ....
Fetch done!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100.00% - 2803 of 2803
Export Accomplished!
Traceback (most recent call last):
  File "/matrix_archive/matrix-archive.py", line 500, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/matrix_archive/matrix-archive.py", line 478, in main
    await write_room_events(client, room)
  File "/matrix_archive/matrix-archive.py", line 461, in write_room_events
    await save_current_avatars(client, room)
  File "/matrix_archive/matrix-archive.py", line 209, in save_current_avatars
    async with aiofiles.open(f"{avatar_dir}/{user.user_id}", "wb") as f:
  File "/usr/local/lib/python3.9/site-packages/aiofiles/base.py", line 75, in __aenter__
    self._obj = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiofiles/threadpool/__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/matrix_archive/chats/.../currentavatars/@l34d3m/n:matrix.org'

so the / in @l34d3m/n is making your script throw the error.
maybe check for invalid/irregular characters in filenames?

i solved this with "sudo mkdir /matrix_archive/chats/.../currentavatars/@l34d3m"

**Comment by MeowOrange** [comment]
Fixed in tag:1.5. I cannot test this though, if the fix works, help me close this issue.
